USE customer_behavior;

select * from customer limit 20;

-- --Q1. what is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS Revenue
FROM customer
GROUP BY gender;

-- --Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- --03. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))),2) AS 'Average Product Rating'
FROM customer
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS DECIMAL(10,2))) DESC
LIMIT 5;

-- --04. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customer 
WHERE shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

-- --Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status;

-- --Q6. which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND (100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- --07. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
	SELECT customer_id, previous_purchases,
		CASE WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
		END AS customer_segment
    FROM customer)
    
SELECT customer_segment, COUNT(*) AS 'Numbber of Customers'
FROM customer_type
GROUP BY customer_segment;


-- --Q8. what are the top 3 most purchased products within each category?
with item_counts as (
	select category,
	item_purchased,
	COUNT(customer_id) as total_orders,
	ROW_NUMBER() over (partition by category order by count(customer_id) DESC) as item_rank
	from customer
	group by category, item_purchased)
    
select category,item_purchased, total_orders, item_rank
from item_counts
where item_rank<=3;


-- --09. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- --Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
